sonar.projectKey=Youhorng_researchhub-ai-rag-system-final-year-project
sonar.organization=youhorng

sonar.sources=.
sonar.exclusions=**/migrations/**,**/__pycache__/**,**/node_modules/**,**/static/**,**/tests/**

sonar.python.version=3.12
sonar.coverage.exclusions=**/**
